image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: 3.8
      PYTHON_ARCH: 32

install:
  - git clone "https://github.com/timknip/pycsg.git"
  - move pycsg externals
  
build_script:
  - python -m unittest discover -v
