environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 32

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32

build_script:
  - ps: git clone https://github.com/timknip/pycsg.git
  - ps: Rename-Item pcysg externals
  - ps: python -m unittest discover -v
